version: "3.8"
services:
    nginx:
        image: nginx:1.18.0
        ports:
            - "80:80"
            - "10002:80"
        volumes:
            - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./docker/nginx/conf.d:/etc/nginx/conf.d"
            - "./docker/nginx/log:/var/log/nginx"
            - ".:/usr/share/nginx/html"
    php:
        image: bitnami/php-fpm:8.1.20
        volumes:
            - "./docker/php/php.ini:/usr/local/etc/php/php.ini"
            - "./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf"
            - "./docker/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
            - ".:/usr/share/nginx/html"
        command: sh -c "/bin/sh /usr/share/nginx/html/run.test.sh"
        # command: sh -c "php-fpm -R"
    mysql:
        image: mysql:8.0.23
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
            MYSQL_ROOT_HOST: "%"
        volumes:
            - "./docker/mysql/data:/var/lib/mysql"
            - "./docker/mysql/conf:/etc/mysql/conf.d"
